// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNclx9Huap4G9-2zkmYTXjrkWsowT9h0U',
    appId: '1:64844720661:web:abff93d06774a35124bc1c',
    messagingSenderId: '64844720661',
    projectId: 'sixth-bonbon-459403-e3',
    authDomain: 'sixth-bonbon-459403-e3.firebaseapp.com',
    storageBucket: 'sixth-bonbon-459403-e3.firebasestorage.app',
    measurementId: 'G-WFD0K755ML',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7ad2n1ihGf_2ySE9drd6XRhvVITdCN9o',
    appId: '1:64844720661:android:4ee19d465781de0d24bc1c',
    messagingSenderId: '64844720661',
    projectId: 'sixth-bonbon-459403-e3',
    storageBucket: 'sixth-bonbon-459403-e3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_w0gTCSV_MMVSpsEGwfH1ekZkQrHGVGU',
    appId: '1:64844720661:ios:e03119e4dc58fc6124bc1c',
    messagingSenderId: '64844720661',
    projectId: 'sixth-bonbon-459403-e3',
    storageBucket: 'sixth-bonbon-459403-e3.firebasestorage.app',
    iosClientId: '64844720661-eie77t8tn8mi3l76ih7l51vft79ittb4.apps.googleusercontent.com',
    iosBundleId: 'com.example.doAnMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_w0gTCSV_MMVSpsEGwfH1ekZkQrHGVGU',
    appId: '1:64844720661:ios:e03119e4dc58fc6124bc1c',
    messagingSenderId: '64844720661',
    projectId: 'sixth-bonbon-459403-e3',
    storageBucket: 'sixth-bonbon-459403-e3.firebasestorage.app',
    iosClientId: '64844720661-eie77t8tn8mi3l76ih7l51vft79ittb4.apps.googleusercontent.com',
    iosBundleId: 'com.example.doAnMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNclx9Huap4G9-2zkmYTXjrkWsowT9h0U',
    appId: '1:64844720661:web:c50edfd6335dfbfb24bc1c',
    messagingSenderId: '64844720661',
    projectId: 'sixth-bonbon-459403-e3',
    authDomain: 'sixth-bonbon-459403-e3.firebaseapp.com',
    storageBucket: 'sixth-bonbon-459403-e3.firebasestorage.app',
    measurementId: 'G-5E8FEPSY7E',
  );

}